development:
  adapter: postgresql
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: fantasy_futbol
  pool: 5
  timeout: 5000
  encoding: unicode

# default: &default
#  adapter: postgresql
#  encoding: unicode
#  pool: 5

# development: 
#  <<: *default
#  adapter: sqlite3
#  database: fantasy_futbol_dev

# test:
#  <<: *default
#  database: fantasy_futbol_test

# production:
#  <<: *default
#  database: fantasy_futbol
